name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive
        run: npm run archive

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            archive/*.zip
            dist/**
